# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='EployeeProfile',
            new_name='Employee',
        ),
        migrations.AddField(
            model_name='review',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.Employee'),
        ),
        migrations.AddField(
            model_name='review',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.Question'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
