# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20170712_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
    ]
