# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_auto_20170712_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='achievements.Review'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default='describe'),
        ),
    ]
