# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_auto_20170712_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Superior',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.RemoveField(
            model_name='review',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='review',
        ),
        migrations.AddField(
            model_name='question',
            name='rank',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='superior',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='achievements.Employee'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='achievements.Employee'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='question',
            field=models.ManyToManyField(related_name='question', to='achievements.Question'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='superior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior', to='achievements.Superior'),
        ),
        migrations.AddField(
            model_name='question',
            name='appraisal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appraisal', to='achievements.Appraisal'),
            preserve_default=False,
        ),
    ]
