# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_auto_20170712_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rank',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10),
        ),
    ]
