# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0012_appraisal_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superior',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='question',
            name='appraisal',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.CharField(choices=[('JR', 'Junior'), ('SP', 'Superior'), ('HR', 'Human Resource')], default='JR', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='rank',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=10),
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='question',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='question',
            field=models.ManyToManyField(to='achievements.Question'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='superior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superior', to='achievements.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Superior',
        ),
    ]
