# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0013_auto_20170717_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='appraisal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='achievements.Appraisal'),
            preserve_default=False,
        ),
    ]
