# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0014_auto_20170717_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rank',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=10),
        ),
    ]
