# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0016_auto_20170717_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 7, 19, 8, 31, 6, 217513, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
